services:
  backend:
    image: merode-interpreter-api
    build:
      context: .
      dockerfile: merode.Dockerfile
    volumes:
      - ./data:/data
    ports:
      - 8081:8080
  dashboard:
    image: nodered/node-red
    volumes:
      - ./node-red/data:/data
    ports:
      - 1880:1880

networks:
  merode:
    driver: bridge
