include:
  - values.yaml

services:
  backend:
    image: localhost/merode-web
    build:
      context: .
      dockerfile: merode.Dockerfile
    ports:
      - 8081:8080
  dashboard:
    image: nodered/node-red
    volumes:
      - node_red_data:/data
    ports:
      - 1880:1880

volumes:
  node_red_data:

networks:
  merode:
    driver: bridge
